version: "3.9"

services:
  api:
    build: ./ChatApp.Api
    container_name: chatapp-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=localhost\SQLEXPRESS;Database=ChatAppDb;Integrated Security=True;TrustServerCertificate=True;
      - Jwt__Key=THIS_IS_DEMO_KEY_CHANGE_IN_PRODUCTION_1234567890
      - Jwt__Issuer=ChatApp
      - Jwt__Audience=ChatAppClient
    ports:
      - "5001:8080"

  mvc:
    build: ./ChatApp.Mvc
    container_name: chatapp-mvc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ChatApiBaseUrl=http://api:8080/
    depends_on:
      - api
    ports:
      - "5002:8080"